version: 2.0
workflows:
  version: 2
  test:
    jobs:
      - python3.6
        
      - python3.7
      - python3.8
jobs:
  python3.6: &template
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job

    steps:
      - checkout  # checkout source code to working directory
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: pip install numpy --user && pip install funkpy --user
      - run: python all-tests.py

  python3.7:
    <<: *template
    docker:
      - image: circleci/python:3.7.6

  python3.8:
    <<: *template
    docker:
      - image: circleci/python:3.8.0
