version: 2.0
workflows:
  version: 2
  test:
    jobs:
      - python3.6
      - python3.7
      - python3.8
jobs:
  python3.6: &template
    working_directory: ~/project
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job

    steps:
      - checkout  # checkout source code to working directory
      # - run: sudo chown -R circleci:circleci /usr/local/bin
      # - run: sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      # - restore_cache:  # ensure this step occurs *before* installing dependencies
      #     key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          command: |  # use pipenv to install dependencies
            pip install numpy
            pip install funkpy
      # - save_cache:
      #     key: deps9-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      #     paths:
      #       - ".venv"
      #       - "/usr/local/bin"
      #       - "/usr/local/lib/python3.6/site-packages"
      - run:
        command: |
          python manage.py test

  python3.7:
    <<: *template
    docker:
      - image: circleci/python:3.7.6

  python3.8:
    <<: *template
    docker:
      - image: circleci/python:3.8.0
